github:
  - denysdovhan
open_collective: spaceship-prompt
buy_me_a_coffee: denysdovhan
patreon: denysdovhan
custom:
  - https://spaceship-prompt.sh/contribute
  - https://www.comebackalive.in.ua/donate
  - https://github.com/vshymanskyy/StandWithUkraine
