pull_request_title: 'docs(i18n): New Crowdin updates'
pull_request_labels:
  - docs
  - translations
commit_message: 'docs(i18n): New translations for %original_file_name% (%language%)'
append_commit_message: false
files:
  - source: /docs/**/*.md
    ignore:
      - /docs/%locale%  # translated files
      - /docs/blog/**/* # blog posts
    translation: /docs/%two_letters_code%/**/%original_file_name%
